CREATE USER "brum4" LOGIN ENCRYPTED PASSWORD 'brum4' VALID UNTIL 'infinity';
CREATE DATABASE "brum4" WITH OWNER = "brum4" ENCODING = 'UTF8' CONNECTION LIMIT = 100;

GRANT ALL ON DATABASE "brum4" TO "brum4";