package brum.model.exception;

public enum ErrorStatusCode {
    // common codes
    SUCCESS,
    INTERNAL_SERVER_ERROR,
    FORBIDDEN,
    ACCOUNT_INACTIVE,
    ACCOUNT_GDPR_LOCKED,
    BEM_ERROR,
    NOT_FOUND,
    FORMAT_NOT_SUPPORTED,
    DOCUMENT_INFO_MISSING,
    PARSING_ERROR,
    NOT_UNIQUE,
    VALIDATION_ERROR,
    FILE_ERROR,
    NO_FILE_PASSED,
    DOCUMENT_IS_PUBLIC,
    IDENTITY_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    ALREADY_REGISTERED,
    NOTIFICATION_SENDING_ERROR,
    IDENTITY_SUSPENDED,
    CODE_NOT_GENERATED,
    IDENTITY_INACTIVE,
    ONE_STEP_PUBLISH_ENABLED,
    IDENTITY_PUBLISHED_ON_DLT,
    USER_NOT_REGISTERED,
    INVALID_PASSWORD,
    NOT_PUBLISHED,
    GROUP_OR_MAP_REQUIRED,
    ACCOUNT_TEMPORARY_BLOCKED
}
